### ISSUE TITLE
have to restart dnsmasq and pause immediately after configuring

### ISSUE THREAD

**Issue by bryanlarsen** [jivesoftware/ansible-consul#14]
have to restart dnsmasq and pause immediately after configuring.   Otherwise the next step (installing tornado) will fail because pypi.python.org doesn't resolve.

```
diff --git a/roles/ansible-consul/tasks/dnsmasq.yml b/roles/ansible-consul/tasks/dnsmasq.yml
index 4686aa1..c960105 100644
--- a/roles/ansible-consul/tasks/dnsmasq.yml
+++ b/roles/ansible-consul/tasks/dnsmasq.yml
@@ -12,5 +12,11 @@
   copy: >
     content='server=/{{ consul_domain }}/127.0.0.1#8600'
     dest=/etc/dnsmasq.d/10-consul
-  notify:
-    - restart dnsmasq
+  register: dnsmasq_configured
+
+- service: name=dnsmasq state=restarted
+  when: dnsmasq_configured|changed
+
+- pause: seconds=1
+  when dnsmasq_configured|changed
+
```

**Comment by trumant** [comment]
I've run into this as well. I'd like a solution that combines the existing handler with a wait_for (http://docs.ansible.com/ansible/wait_for_module.html) task but AFAIK there is no way to build a handler composed of a chain of multiple tasks

**Comment by trumant** [comment]
This should be able to be closed now
